import { Category, Product, Profile } from "../types/types";

export const categoryNames: Category[] = [
  {
    id: 1,
    name: "Low prices",
  },
  {
    id: 2,
    name: "All",
  },
  {
    id: 3,
    name: "Sports",
  },
];

export const products: Product[] = [
  {
    id: 1,
    name: "T-Shirt. Blue",
    group: "Clothes",
    ranking: 4.8,
    reviews: 11285,
    price: 16.99,
    image: "src/assets/img/t-shirt.png",
    seller: "ClothesShop",
    deliveryTime: "1 day",
    deliveryPrice: "free",
    quantity: 26,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dignissim enim sit amet venenatis urna cursus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Mi sit amet mauris commodo quis imperdiet. Sed viverra ipsum nunc aliquet bibendum enim. Ullamcorper eget nulla facilisi etiam. Id porta nibh venenatis cras sed. Tellus cras adipiscing enim eu turpis egestas pretium. Tincidunt eget nullam non nisi est sit amet facilisis magna. Dui faucibus in ornare quam. Ullamcorper eget nulla facilisi etiam dignissim. In tellus integer feugiat scelerisque varius morbi enim. Luctus accumsan tortor posuere ac ut consequat. Elementum eu facilisis sed odio morbi quis commodo. Euismod quis viverra nibh cras pulvinar. At risus viverra adipiscing at in tellus. Aliquam nulla facilisi cras fermentum odio. Eu ultrices vitae auctor eu augue ut lectus arcu bibendum. Vitae congue mauris rhoncus aenean vel elit. Mi eget mauris pharetra et ultrices neque ornare aenean euismod. Consectetur libero id faucibus nisl tincidunt eget nullam non. Enim lobortis scelerisque fermentum dui faucibus in ornare quam. Leo in vitae turpis massa. Dictumst quisque sagittis purus sit. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper eget. Quam adipiscing vitae proin sagittis nisl rhoncus mattis. Etiam tempor orci eu lobortis elementum nibh tellus molestie nunc. Id velit ut tortor pretium viverra suspendisse potenti nullam ac. Posuere ac ut consequat semper viverra nam libero justo laoreet. Rhoncus dolor purus non enim. \n\nMagna fringilla urna porttitor rhoncus dolor. Bibendum ut tristique et egestas. Aliquet eget sit amet tellus cras adipiscing enim. Eget mauris pharetra et ultrices. Laoreet sit amet cursus sit amet dictum sit amet justo. Sit amet nisl purus in mollis. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Euismod in pellentesque massa placerat. Vel risus commodo viverra maecenas. Id diam vel quam elementum pulvinar etiam non. Sed augue lacus viverra vitae congue. Eu volutpat odio facilisis mauris sit amet. Augue eget arcu dictum varius duis. Risus commodo viverra maecenas accumsan. Ipsum nunc aliquet bibendum enim facilisis. Felis bibendum ut tristique et. Dignissim cras tincidunt lobortis feugiat. Pellentesque pulvinar pellentesque habitant morbi tristique. Nullam eget felis eget nunc lobortis mattis aliquam faucibus purus. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. In fermentum posuere urna nec tincidunt praesent semper feugiat. Tellus elementum sagittis vitae et leo duis ut diam quam. Nisi porta lorem mollis aliquam. Orci dapibus ultrices in iaculis nunc sed augue lacus. Nibh tortor id aliquet lectus proin. Magnis dis parturient montes nascetur ridiculus mus mauris vitae ultricies. Auctor neque vitae tempus quam pellentesque nec nam. Tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras fermentum. Placerat orci nulla pellentesque dignissim enim. Molestie a iaculis at erat pellentesque adipiscing commodo elit at. Tincidunt tortor aliquam nulla facilisi cras fermentum odio. Tincidunt praesent semper feugiat nibh sed pulvinar. Praesent tristique magna sit amet purus. A erat nam at lectus. Aliquam id diam maecenas ultricies. Nunc non blandit massa enim nec dui. Tempus egestas sed sed risus pretium. Auctor elit sed vulputate mi sit amet. Vel pretium lectus quam id leo in. Tempus quam pellentesque nec nam. Lectus proin nibh nisl condimentum id venenatis a.",
    comments: [
      {
        client: "John Terry",
        rating: 5,
        commentText: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dignissim enim sit amet venenatis urna cursus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Mi sit amet mauris commodo quis imperdiet. Sed viverra ipsum nunc aliquet bibendum enim. Ullamcorper eget nulla facilisi etiam. Id porta nibh venenatis cras sed. Tellus cras adipiscing enim eu turpis egestas pretium. Tincidunt eget nullam non nisi est sit amet facilisis magna. Dui faucibus in ornare quam. Ullamcorper eget nulla facilisi etiam dignissim. In tellus integer feugiat scelerisque varius morbi enim. Luctus accumsan tortor posuere ac ut consequat.",
      },
      {
        client: "Frank Lampard",
        rating: 4,
        commentText: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dignissim enim sit amet venenatis urna cursus. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Mi sit amet mauris commodo quis imperdiet. Sed viverra ipsum nunc aliquet bibendum enim. Ullamcorper eget nulla facilisi etiam. Id porta nibh venenatis cras sed. Tellus cras adipiscing enim eu turpis egestas pretium. Tincidunt eget nullam non nisi est sit amet facilisis magna. Dui faucibus in ornare quam. Ullamcorper eget nulla facilisi etiam dignissim. In tellus integer feugiat scelerisque varius morbi enim. Luctus accumsan tortor posuere ac ut consequat.",
      },
    ],
  },
  {
    id: 2,
    name: "T-Shirt. Blue",
    group: "Clothes",
    ranking: 4.8,
    reviews: 11285,
    price: 16.99,
    image: "src/assets/img/t-shirt.png",
    seller: "ClothesShop",
    deliveryTime: "1 day",
    deliveryPrice: "free",
    quantity: 26,
  },
  {
    id: 3,
    name: "T-Shirt. Blue",
    group: "Clothes",
    ranking: 4.8,
    reviews: 11285,
    price: 16.99,
    image: "src/assets/img/t-shirt.png",
    seller: "ClothesShop",
    deliveryTime: "1 day",
    deliveryPrice: "free",
    quantity: 26,
  },
  {
    id: 4,
    name: "T-Shirt. Blue",
    group: "Clothes",
    ranking: 4.8,
    reviews: 11285,
    price: 16.99,
    image: "src/assets/img/t-shirt.png",
    seller: "ClothesShop",
    deliveryTime: "1 day",
    deliveryPrice: "free",
    quantity: 26,
  },
  {
    id: 5,
    name: "T-Shirt. Blue",
    group: "Clothes",
    ranking: 4.8,
    reviews: 11285,
    price: 16.99,
    image: "src/assets/img/t-shirt.png",
    seller: "ClothesShop",
    deliveryTime: "1 day",
    deliveryPrice: "free",
    quantity: 26,
  },
  {
    id: 6,
    name: "T-Shirt. Blue",
    group: "Clothes",
    ranking: 4.8,
    reviews: 11285,
    price: 16.99,
    image: "src/assets/img/t-shirt.png",
    seller: "ClothesShop",
    deliveryTime: "1 day",
    deliveryPrice: "free",
    quantity: 26,
  },
  {
    id: 7,
    name: "T-Shirt. Blue",
    group: "Clothes",
    ranking: 4.8,
    reviews: 11285,
    price: 16.99,
    image: "src/assets/img/t-shirt.png",
    seller: "ClothesShop",
    deliveryTime: "1 day",
    deliveryPrice: "free",
    quantity: 26,
  },
  {
    id: 8,
    name: "T-Shirt. Blue",
    group: "Clothes",
    ranking: 4.8,
    reviews: 11285,
    price: 16.99,
    image: "src/assets/img/t-shirt.png",
    seller: "ClothesShop",
    deliveryTime: "1 day",
    deliveryPrice: "free",
    quantity: 26,
  },
];

export const profileData: Omit<Profile, "id"> = {
  name: "",
  email: "",
  password: "",
  confirmPassword: "",
};

export const token: string = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c";
